---
- hosts: all
  vars:
    applications:
      - alfred # | http://www.alfredapp.com
      - apptrap # remove associated prefs when uninstalling
      - appzapper # uninstaller
      - atom # sublime without annoying popup | https://atom.io/download/mac
      - bettertouchtool # window snapping. (maybe Moom is more lightweight?)
      - bodega # a less-shit mac store
      - carbon-copy-cloner # backups | https://bombich.com/download
      - cheatsheet # know your shortcuts
      - cyberduck # ftp, s3, openstack
      - dash # totally sick API browser
      - diffmerge # free visual diq
      - dropbox # a worse Mega Sync
      - eve # learn your shortcuts
      - firefox
      - flux # get more sleep
      - google-chrome
      - handbrake # vid compression
      - imageoptim # optimize images
      - istumbler # network discovery GUI
      - iterm2
      - jumpcut # awesome clipboard
      - megasync # a better Dropbox
      - monolingual # remove unneeded osx lang files
      - nvalt # fast note taking
      - packer # machine images
      - qlcolorcode # quick look syntax highlighting
      - qlimagesize # quick look image dimensions
      - qlmarkdown # quick look .md files
      - qlstephen # quick look extension-less text files
      - rowanj-gitx # Awesome gitx fork.
      - shuttle # ssh management
      - torbrowser # be the noise
      - transmission # torrents
      - vagrant # | https://www.vagrantup.com/downloads.html
      - vagrant-manager #
      - virtualbox # | https://www.virtualbox.org/
      - vlc

    install_oh_my_zsh:  true

    dotfile_repo_username: glennr # the GH repo where your dotfiles are

    brew_utils:
      # - ansible #already installed by ./mac bootstrap script
      - autoconf
      - autojump # quickly navigate from cmd line
      - bash # Bash 4
      - brew-cask
      - cowsay # amazing
      - coreutils # Install GNU core utilities (those that come with OS X are outdated)
      # - ctags
      - docker # | https://docs.docker.com/installation/mac/
      # - ffmpeg
      - findutils  # Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
      - git
      - go
      - gpg
      #-  homebrew/dupes/grep # more recent version of OS X grep # ansible bug: https://github.com/ansible/ansible-modules-extras/issues/252
      - hub # github
      # - imagemagick # IDK why, but I always end up needing this beast
      - keybase # in alpha at time of writing.
      # - mongodb # a shittier PG
      - mtr # better traceroute
      - node
      - npm
      - openssl
      - packer
      # - phantomjs
      # - postgresql # yes and nosql
      - python
      - rbenv # ruby. Just installs binaries - assumes you bring in the dotfiles.
      - readline
      - redis
      - rename # rename multiple files
      - rsync
      - ruby-build
      - sqlite # production rails DB
      - the_silver_searcher # fast ack-grep
      - tmux
      - vim
      - wget
      - zsh

    # zsh_path: /usr/local/bin/zsh

    home: "{{ lookup('env','HOME') }}"

  tasks:
    - name: Check Homebrew is installed
      stat: path=/usr/local/bin/brew
      register: brew_installed

    - name: Install Homebrew
      shell: ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
      when: brew_installed.stat.exists == false

    - name: Check homebrew-cask is installed
      stat: path=/usr/local/bin/brew-cask.rb
      register: brew_cask_installed

    ### UTILS

    - name: Install libraries/utils with homebrew
      homebrew: name={{ item }} state=present
      # with_items: brew_utils
      with_items:
              - autoconf
              - autojump # quickly navigate from cmd line
              - bash # Bash 4
              - cowsay # amazing
              - coreutils # Install GNU core utilities (those that come with OS X are outdated)
              # - ctags
              - docker # | https://docs.docker.com/installation/mac/
              # - ffmpeg
              - findutils  # Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
              - git
              - go
              - gpg
              #-  homebrew/dupes/grep # more recent version of OS X grep # ansible bug: https://github.com/ansible/ansible-modules-extras/issues/252
              - hub # github
              # - imagemagick # IDK why, but I always end up needing this beast
              - mongodb # a shittier PG
              - mtr # better traceroute
              - node
              - npm
              - openssl
              - packer
              # - phantomjs
              # - postgresql # yes and nosql
              - python
              - rbenv # ruby. Just installs binaries - assumes you bring in the dotfiles.
              - readline
              - redis
              - rename # rename multiple files
              - rsync
              - ruby-build
              - sqlite # production rails DB
              - the_silver_searcher # fast ack-grep
              - tmux
              - vim
              - wget
              - zsh


    - name: Cleanup after brewing
      shell: brew cleanup


    ### APPZ

    - name: Check for installed apps(casks)
      shell: brew cask list | grep {{ item }}
      register: installed_applications
      # with_items: applications
      with_items:
              - alfred # | http://www.alfredapp.com
              - apptrap # remove associated prefs when uninstalling
              - appzapper # uninstaller
              - atom # sublime without annoying popup | https://atom.io/download/mac
              - bettertouchtool # window snapping. (maybe Moom is more lightweight?)
              - bodega # a less-shit mac store
              - carbon-copy-cloner # backups | https://bombich.com/download
              - cheatsheet # know your shortcuts
              - cyberduck # ftp, s3, openstack
              - dash # totally sick API browser
              - diffmerge # free visual diq
              - dropbox # a worse Mega Sync
              - eve # learn your shortcuts
              - firefox
              - flux # get more sleep
              - google-chrome
              - handbrake # vid compression
              - imageoptim # optimize images
              - istumbler # network discovery GUI
              - iterm2
              - jumpcut # awesome clipboard
              - megasync # a better Dropbox
              - monolingual # remove unneeded osx lang files
              - nvalt # fast note taking
              - packer # machine images
              - qlcolorcode # quick look syntax highlighting
              - qlimagesize # quick look image dimensions
              - qlmarkdown # quick look .md files
              - qlstephen # quick look extension-less text files
              - rowanj-gitx # Awesome gitx fork.
              - shuttle # ssh management
              - torbrowser # be the noise
              - transmission # torrents
              - vagrant # | https://www.vagrantup.com/downloads.html
              - vagrant-manager #
              - virtualbox # | https://www.virtualbox.org/
              - vlc

      ignore_errors: true

    - name: Install Apps with brew-cask
      shell: brew cask install {{ item }}
      # with_items: applications
      with_items:
              - alfred # | http://www.alfredapp.com
              - apptrap # remove associated prefs when uninstalling
              - appzapper # uninstaller
              - atom # sublime without annoying popup | https://atom.io/download/mac
              - bettertouchtool # window snapping. (maybe Moom is more lightweight?)
              - bodega # a less-shit mac store
              - carbon-copy-cloner # backups | https://bombich.com/download
              - cheatsheet # know your shortcuts
              - cyberduck # ftp, s3, openstack
              - dash # totally sick API browser
              - diffmerge # free visual diq
              - dropbox # a worse Mega Sync
              - eve # learn your shortcuts
              - firefox
              - flux # get more sleep
              - google-chrome
              - handbrake # vid compression
              - imageoptim # optimize images
              - istumbler # network discovery GUI
              - iterm2
              - jumpcut # awesome clipboard
              - megasync # a better Dropbox
              - monolingual # remove unneeded osx lang files
              - nvalt # fast note taking
              - packer # machine images
              - qlcolorcode # quick look syntax highlighting
              - qlimagesize # quick look image dimensions
              - qlmarkdown # quick look .md files
              - qlstephen # quick look extension-less text files
              - rowanj-gitx # Awesome gitx fork.
              - shuttle # ssh management
              - torbrowser # be the noise
              - transmission # torrents
              - vagrant # | https://www.vagrantup.com/downloads.html
              - vagrant-manager #
              - virtualbox # | https://www.virtualbox.org/
              - vlc
      when: "{{ item not in installed_applications.results|map(attribute='stdout') }}"

    # Caveats: megasync only works if called from /Applications
    - name: Linking MEGASync with brew-cask
      shell: ln -s '/opt/homebrew-cask/Caskroom/megasync/latest/MEGAsync.app' '/Applications/MEGAsync.app'
      when: "'megasync' in applications"
      ignore_errors: true # hacky

    ### ZSH radness
    - name: Determine if zsh is default/current shell
      shell: echo $SHELL
      register: current_shell

    - name: Enable zsh in /etc/shells
      shell: sudo /bin/sh -c 'grep -q "{{ zsh_path }}" /etc/shells || echo "{{ zsh_path }}" >> /etc/shells'
      when: current_shell.stdout != '/usr/local/bin/zsh'

    # - name: Set zsh as default shell
    #  shell: chsh -s {{ zsh_path }}
    #  when: current_shell.stdout != '/usr/local/bin/zsh'
    #  sudo: true

    - name: Use GNU tools instead of osx counterparts (grep find etc)
      shell: echo 'export PATH=$(brew --prefix coreutils)/libexec/gnubin:$PATH' >> ~/.zshrc

    - name: Install oh-my-zsh
      git: repo=https://github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh
      sudo: false
      when: install_oh_my_zsh == true
      tags: install_oh_my_zsh

    ### OSX SETTINGS

    - name: Configure System Settings
      # script: scripts/system_settings.sh
      script: scripts/minimal_system_settings.sh
      sudo: true
